# -*- coding: utf-8 -*-
"""apsche_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nEEy7R_fl7h6AJpkuz2TdGXR0wXgHw9r
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("rupakroy/online-payments-fraud-detection-dataset")

print("Path to dataset files:", path)

"""


**Import the necessary libraries **

Read the Dataset
Our dataset format might be in .csv, excel files, .txt, .json, etc. We can read the dataset with the help of pandas.

In pandas we have a function called read_csv() to read the dataset. As a parameter we have to give the directory of the csv file."""

import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Construct the full path to the CSV file
dataset_file_path = os.path.join(path, 'PS_20174392719_1491204439457_log.csv')

# Load the dataset
df = pd.read_csv(dataset_file_path)

# Display the first 5 rows of the DataFrame
display(df.head())

# Display information about the DataFrame, including data types and non-null values
df.info()

# Shape of csv data
df.shape

df.drop(['nameOrig','nameDest'],axis=1,inplace=True)
df.columns

# Remove the Outliers
from scipy import stats
print(stats.mode(df['amount']))
print(np.mean(df['amount']))

q1 = np.quantile(df['amount'],0.25)
q3 = np.quantile(df['amount'],0.75)

IQR = q3 - q1

upper_bound = q3 + (1.5 * IQR)
lower_bound = q1 - (1.5 * IQR)

print('q1 :',q1)
print('q3 :',q3)
print('IQR :',IQR)
print('Upper Bound :',upper_bound)
print('Lower Bound :',lower_bound)
print('Skewed data :',len(df[df['amount'] > upper_bound]))
print('Skewed data :',len(df[df['amount'] < lower_bound]))

# Remove the Outliers
from scipy import stats
print(stats.mode(df['amount']))
print(np.mean(df['amount']))

q1 = np.quantile(df['amount'],0.25)
q3 = np.quantile(df['amount'],0.75)

IQR = q3 - q1

upper_bound = q3 + (1.5 * IQR)
lower_bound = q1 - (1.5 * IQR)

print('q1 :',q1)
print('q3 :',q3)
print('IQR :',IQR)
print('Upper Bound :',upper_bound)
print('Lower Bound :',lower_bound)
print('Skewed data :',len(df[df['amount'] > upper_bound]))
print('Skewed data :',len(df[df['amount'] < lower_bound]))

# To handle outliers transformation techniques are used.
def transformation(feature):
    plt.figure(figsize=(12,5))
    plt.subplot(1,2,1)
    sns.distplot(feature)
    plt.subplot(1,2,2)
    stats.probplot(feature,plot=plt)

# Object Data Labelencoding
from sklearn.preprocessing import LabelEncoder

la = LabelEncoder()
df['type'] = la.fit_transform(df['type'])

df['type'].value_counts()

# dividing the dataset into dependent and independent y and x respectively
x = df.drop('isFraud',axis=1)
y = df['isFraud']

x

# Train test split
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0,test_size=0.2)

print(x_train.shape)
print(x_test.shape)
print(y_test.shape)
print(y_train.shape)

# Random Forest classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

rfc = RandomForestClassifier()
rfc.fit(x_train,y_train)

y_test_predict1 = rfc.predict(x_test)
test_accuracy = accuracy_score(y_test,y_test_predict1)
test_accuracy

y_train_predict1 = rfc.predict(x_train)
train_accuracy = accuracy_score(y_train,y_train_predict1)
train_accuracy

pd.crosstab(y_test,y_test_predict1)

print(classification_report(y_test,y_test_predict1))

# Decision Tree classifier
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()
dtc.fit(x_train,y_train)

y_test_predict2 = dtc.predict(x_test)
test_accuracy = accuracy_score(y_test,y_test_predict2)
test_accuracy

y_train_predict2 = dtc.predict(x_train)
train_accuracy = accuracy_score(y_train,y_train_predict2)
train_accuracy

pd.crosstab(y_test,y_test_predict2)

print(classification_report(y_test,y_test_predict2))

# Extra Trees classifier
from sklearn.ensemble import ExtraTreesClassifier

etc = ExtraTreesClassifier()
etc.fit(x_train,y_train)

y_test_predict3 = etc.predict(x_test)
test_accuracy = accuracy_score(y_test,y_test_predict3)
test_accuracy

y_train_predict3 = etc.predict(x_train)
train_accuracy = accuracy_score(y_train,y_train_predict3)
train_accuracy

pd.crosstab(y_test,y_test_predict3)

print(classification_report(y_test,y_test_predict3))

# SVM classifier
from sklearn.svm import SVC

svc = SVC()
svc.fit(x_train,y_train)

y_test_predict4 = svc.predict(x_test)
test_accuracy = accuracy_score(y_test,y_test_predict4)
test_accuracy

y_train_predict4 = svc.predict(x_train)
train_accuracy = accuracy_score(y_train,y_train_predict4)
train_accuracy

pd.crosstab(y_test,y_test_predict4)

from sklearn.metrics import classification_report,confusion_matrix

print(classification_report(y_test,y_test_predict4))

df.columns

from sklearn.preprocessing import LabelEncoder

la = LabelEncoder()
y_train1 = la.fit_transform(y_train)

y_test1 = la.transform(y_test)

y_test1

y_train1

import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

xgb1 = xgb.XGBClassifier()
xgb1.fit(x_train, y_train1)

y_test_predict5 = xgb1.predict(x_test)
test_accuracy = accuracy_score(y_test1, y_test_predict5)
test_accuracy

y_train_predict5 = xgb1.predict(x_train)
train_accuracy = accuracy_score(y_train1, y_train_predict5)
train_accuracy

pd.crosstab(y_test1, y_test_predict5)

print(classification_report(y_test1, y_test_predict5))

# Compare Models
def compareModel():
    print("train accuracy for rfc", accuracy_score(y_train_predict1, y_train))
    print("test accuracy for rfc", accuracy_score(y_test_predict1, y_test))

    print("train accuracy for dtc", accuracy_score(y_train_predict2, y_train))
    print("test accuracy for dtc", accuracy_score(y_test_predict2, y_test))

    print("train accuracy for etc", accuracy_score(y_train_predict3, y_train))
    print("test accuracy for etc", accuracy_score(y_test_predict3, y_test))

    print("train accuracy for svc", accuracy_score(y_train_predict4, y_test))
    print("test accuracy for svc", accuracy_score(y_test_predict4, y_test))

    print("train accuracy for xgb1", accuracy_score(y_train_predict5, y_train1))
    print("test accuracy for xgb1", accuracy_score(y_test_predict5, y_test1))

compareModel()

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

svc = SVC()
svc.fit(x_train, y_train)

y_test_predict4 = svc.predict(x_test)
test_accuracy = accuracy_score(y_test, y_test_predict4)
test_accuracy

y_train_predict4 = svc.predict(x_train)
train_accuracy = accuracy_score(y_train, y_train_predict4)
train_accuracy

import pickle
pickle.dump(svc, open('payments.pkl', 'wb'))